In [281]:
# RUN THIS COMMAND ONLY IF YOU USE GOOGLE COLAB.
#from google.colab import drive
#drive.mount('/content/drive')

In [282]:
# RUN THIS COMMAND ONLY IF YOU USE GOOGLE COLAB.
%cd drive/MyDrive/TechLabs/02_Data\ Manipulation/Part\ C\ -\ Pandas

[Errno 2] No such file or directory: 'drive/MyDrive/TechLabs/02_Data Manipulation/Part C - Pandas'
/home/cakir/TechLabs/02_Data Manipulation/Part C - Pandas

/home/cakir/TechLabs/venv/lib/python3.12/site-packages/IPython/core/magics/osm.py:393: UserWarning: This is now an optional IPython functionality, using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks', {})

# Chapter 6 - Add and Remove Rows and Columns From DataFrames 
### Hey Techie,   
Welcome to the sixth notebook of this Pandas tutorial series. We encourage you to take this notebook as a template to code along the instruction video, which you may find at: https://youtu.be/HQ6XO9eT-fc. In the instruction video, Corey explains adding and removing columns and rows to and from DataFrames. At the notebook's end, you find practice tasks to test your newly gained knowledge with the real-world survey data we already know.   

**Here you may find the Pandas documentation:** https://pandas.pydata.org/docs/reference/index.html

#### Have fun! :-)   
    
*Video length*: 17 minutes   
*Self-study time*: 17 minutes   
*Total*: **34 minutes**
<hr style="border:2px solid gray"> </hr>   

## Code-Snippets

In [283]:
# This is the convention used to import Pandas.
import pandas as pd

In [284]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [285]:
# START YOUR CODE HERE.
df = pd.DataFrame(people)
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [286]:
# Adding columns
df['full_name'] = df['first'] + ' ' + df['last'] # easy just write the column name that you wanna name it and the values
df

   first     last                    email      full_name
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe

In [287]:
# removing column
df.drop(columns=['first','last'],inplace=True) # to remove columns we use the drop method and give the parameters as columns=[] for more than one column
df

                     email      full_name
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe

In [288]:
df[['first','last']] = df['full_name'].str.split(' ', expand=True) # split full_name column in two columns
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe

In [289]:
# add rows and data
# adding a simple row
df._append({'first':'Tony'}, ignore_index=True) # to add a row we use the _append method and give the parameters as a dictionary with the column name as key and the value as value

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN

In [290]:
people = {
    "first": ["Tony", 'Steve'], 
    "last": ["Stark", 'Rogers'], 
    "email": ["ironman@avenge.com", 'Cap@avenge.com']
}

df2 = pd.DataFrame(people)
df2

   first    last               email
0   Tony   Stark  ironman@avenge.com
1  Steve  Rogers      Cap@avenge.com

In [291]:
df = df._append(df2,ignore_index=True, sort=False) # to add multiple rows we use the _append method and give the dataframe that we wanna append, ignore_index=True to reset the index

In [292]:
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3       ironman@avenge.com            NaN   Tony    Stark
4           Cap@avenge.com            NaN  Steve   Rogers

In [293]:
# Remove rows
df.drop(index=4,inplace= True) # index 4(actually 5) remove
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3       ironman@avenge.com            NaN   Tony    Stark

In [294]:
df.drop(index = df[df['last'] == 'Doe'].index) # remove all rows where last name is Doe

filt = df['last'] == 'Doe'
df.drop(index = df[filt].index) # same as above

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
3       ironman@avenge.com            NaN   Tony    Stark

<hr style="border:2px solid gray"> </hr>   
   
## Practice Tasks

In [295]:
# These options help us to inspect our data more easily.
pd.set_option("display.max_columns", 85)
pd.set_option("display.max_rows", 85)
# Load a clean DataFrame.
df = pd.read_csv("data/survey_results_public.csv", index_col = "Respondent")

#### 1. Below you will find information for a new row. Add it to the survey DataFrame. 
<br /> 
<details>    
<summary>
    <font size="3" color="red"><b>Hints (click to expand)</b></font>
</summary>
<p>
    <ul>
        <li>One can use the append-method to add a row to a DataFrame.</li>
        <li>The append-method returns a new DataFrame. In this case, there is no inplace-argument.</li>
        <li>As we are applying a dictionary, set the ignore_index-argument to True.</li>
    </ul>
</p>
</details>

In [296]:
new_row = {"MainBranch": "I am a student who is learning to code", 
           "Hobbyist": "Yes",
           "OpenSourcer": "Once a month or more often",
           "Employment": "Employed part-time",
           "Country": "Germany",
           "Student": "Yes, full-time"}
# START YOUR CODE HERE.

df = df._append(new_row, ignore_index=True)

# END YOUR CODE HERE.

In [297]:
# THIS CELL TESTS YOUR RESULTS.
assert df.iloc[-1, 1] == "Yes", "It seems that adding the new row to the DataFrame did not work!"
assert df.iloc[-1, 4] == "Employed part-time", "It seems that adding the new row to the DataFrame did not work!"
assert df.shape[0] == 88884, "It seems that adding the new row to the DataFrame did not work!"

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>df = df.append(new_row, ignore_index = True)</code>
</p>
</details>   
   
#### 2. Below you will find three columns that appear to contain many NaN values. Remove these columns from the survey DataFrame.
<br />
<details>    
<summary>
    <font size="3" color="red"><b>Hints (click to expand)</b></font>
</summary>
<p>
    <ul>
        <li>One can use the drop-method to drop rows/columns from a DataFrame.</li>
        <li>As we are trying to drop columns, what value should we the axis-argument assign to?</li>
        <li>Remind yourself of the inplace-argument.</li>
    </ul>
</p>
</details>

In [298]:
columns_drop = ["BlockchainOrg", "CodeRevHrs", "ConvertedComp"]
# START YOUR CODE HERE.

df.drop(columns=columns_drop,inplace=True)

# END YOUR CODE HERE.

In [299]:
# THIS CELL TESTS YOUR RESULTS.
assert "BlockchainOrg" not in df.columns, "As it seems you did not drop the BlockchainOrg column."
assert "CodeRevHrs" not in df.columns, "As it seems you did not drop the CodeRevHrs column."
assert "ConvertedComp" not in df.columns, "As it seems you did not drop the ConvertedComp column."

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>df.drop(labels = columns_drop, axis = "columns", inplace = True)</code>
</p>
</details>   
   
#### 3. Drop every survey respondent who is not resident in the US.

<br />
<details>    
<summary>
    <font size="3" color="red"><b>Hints (click to expand)</b></font>
</summary>
<p>
    <ul>
        <li>Remind yourself of conditionals to filter DataFrames.</li>
        <li>One can negate a filter by using the ~-operator.</li> 
        <li>To drop rows from a DataFrame, you need the row indexes.</li>
        <li>One can use the drop-method to drop rows/columns from a DataFrame.</li>
        <li>As we are trying to drop columns, what value should we the axis-argument assign to?</li>
        <li>Remind yourself of the inplace-argument.</li>
    </ul>
        
</p>
</details>

In [302]:
# START YOUR CODE HERE.

# DEFINE A FILTER HERE.
filt = df['Country'] != 'United States'
# DROP THE ROWS HERE.
df.drop(index=df[filt].index, inplace=True)

# END YOUR CODE HERE.

In [303]:
# THIS CELL TESTS YOUR RESULTS.
assert len(df["Country"].unique()) == 1, "Your filter seems to not work!"
assert df["Country"].unique()[0] == "United States", "You did not extract residents from the US!"

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>filt = ~(df["Country"] == "United States")</code><br />
    <code>df.drop(labels = df.loc[filt].index, axis = "rows", inplace = True)</code>
</p>
</details>